name: Gradle build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out 
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle setup
        uses: gradle/gradle-build-action@v2
      - name: Gradle build
        run: ./gradlew build

    